### ISSUE TITLE
segfault reported on Julia Users

### ISSUE THREAD

**Issue by catawbasam** [JuliaWeb/HttpServer.jl#46] opened 2015-02-13 22:49 UTC
https://groups.google.com/forum/?fromgroups=#!topic/julia-users/2a26Fwu3Fwc

**Comment by ihnorton** [comment] 2015-02-14 03:47
Dupe of https://github.com/JuliaWeb/Morsel.jl/issues/33

**Closed** 2015-02-21 08:02 UTC
