### ISSUE TITLE
Can not install on 1.1

### ISSUE THREAD

**Issue by Roger-luo** [JuliaWeb/HttpServer.jl#144] opened 2019-02-15 13:30 UTC
Tried `add HttpServer` on 1.1, got

```
ERROR: Unsatisfiable requirements detected for package HttpParser [38bc9a14]:
 HttpParser [38bc9a14] log:
 ├─possible versions are: [0.0.1-0.0.13, 0.1.0-0.1.1, 0.2.0, 0.3.0-0.3.1, 0.4.0] or uninstalled
 ├─restricted to versions 0.0.0-* by HttpServer [58cfbd8c], leaving only versions [0.0.1-0.0.13, 0.1.0-0.1.1, 0.2.0, 0.3.0-0.3.1, 0.4.0]
 │ └─HttpServer [58cfbd8c] log:
 │   ├─possible versions are: 0.3.1 or uninstalled
 │   └─HttpServer [58cfbd8c] is fixed to version 0.3.1+
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by ararslan** [comment] 2019-02-15 19:50
Duplicate of https://github.com/JuliaWeb/HttpServer.jl/issues/140. The [HTTP](https://github.com/JuliaWeb/HTTP.jl) package should be used instead.

**Closed by ararslan** 2019-02-15 19:50 UTC
